# Generated by Django 4.2.7 on 2025-01-24 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_add_new_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(help_text='ID único del trabajo', max_length=100, unique=True)),
                ('job_type', models.CharField(choices=[('regression', 'Modelo de Regresión'), ('vision', 'Modelo de Visión (YOLOv8)'), ('incremental', 'Entrenamiento Incremental')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'Ejecutándose'), ('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('model_name', models.CharField(help_text='Nombre del modelo a entrenar', max_length=100)),
                ('dataset_size', models.PositiveIntegerField(help_text='Número de imágenes en el dataset')),
                ('epochs', models.PositiveIntegerField(default=100)),
                ('batch_size', models.PositiveIntegerField(default=16)),
                ('learning_rate', models.FloatField(default=0.001)),
                ('config_params', models.JSONField(default=dict, help_text='Parámetros adicionales de configuración')),
                ('metrics', models.JSONField(default=dict, help_text='Métricas de entrenamiento')),
                ('model_path', models.CharField(blank=True, help_text='Ruta del modelo entrenado', max_length=500, null=True)),
                ('logs', models.TextField(blank=True, help_text='Logs del entrenamiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si falló')),
                ('progress_percentage', models.FloatField(default=0.0, help_text='Porcentaje de progreso')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trabajo de Entrenamiento',
                'verbose_name_plural': 'Trabajos de Entrenamiento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trainingjob',
            index=models.Index(fields=['status'], name='api_trainin_status_8b2b0b_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingjob',
            index=models.Index(fields=['job_type'], name='api_trainin_job_typ_3a8b0b_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingjob',
            index=models.Index(fields=['created_by', '-created_at'], name='api_trainin_created_8b2b0b_idx'),
        ),
    ]


