# Generated by Django 5.0.8 on 2025-01-24 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_training_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la finca', max_length=200)),
                ('ubicacion', models.CharField(help_text='Dirección o ubicación de la finca', max_length=300)),
                ('municipio', models.CharField(help_text='Municipio donde se encuentra la finca', max_length=100)),
                ('departamento', models.CharField(help_text='Departamento donde se encuentra la finca', max_length=100)),
                ('hectareas', models.DecimalField(decimal_places=2, help_text='Área total de la finca en hectáreas', max_digits=10)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional de la finca', null=True)),
                ('coordenadas_lat', models.DecimalField(blank=True, decimal_places=7, help_text='Latitud GPS de la finca', max_digits=10, null=True)),
                ('coordenadas_lng', models.DecimalField(blank=True, decimal_places=7, help_text='Longitud GPS de la finca', max_digits=10, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro de la finca')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la finca está activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agricultor', models.ForeignKey(help_text='Agricultor propietario de la finca', on_delete=django.db.models.deletion.CASCADE, related_name='fincas', to='auth.user')),
            ],
            options={
                'verbose_name': 'Finca',
                'verbose_name_plural': 'Fincas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(help_text='Identificador único del lote dentro de la finca', max_length=50)),
                ('variedad', models.CharField(help_text='Variedad de cacao del lote', max_length=100)),
                ('fecha_plantacion', models.DateField(help_text='Fecha de plantación del lote')),
                ('fecha_cosecha', models.DateField(blank=True, help_text='Fecha de cosecha del lote', null=True)),
                ('area_hectareas', models.DecimalField(decimal_places=2, help_text='Área del lote en hectáreas', max_digits=8)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('cosechado', 'Cosechado'), ('renovado', 'Renovado')], default='activo', help_text='Estado actual del lote', max_length=20)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional del lote', null=True)),
                ('coordenadas_lat', models.DecimalField(blank=True, decimal_places=7, help_text='Latitud GPS del lote', max_digits=10, null=True)),
                ('coordenadas_lng', models.DecimalField(blank=True, decimal_places=7, help_text='Longitud GPS del lote', max_digits=10, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro del lote')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el lote está activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finca', models.ForeignKey(help_text='Finca a la que pertenece el lote', on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='api.finca')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['-created_at'],
            },
        ),
        # migrations.AddField(
        #     model_name='cacaoimage',
        #     name='lote',
        #     field=models.ForeignKey(blank=True, help_text='Lote al que pertenece esta imagen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cacao_images', to='api.lote'),
        # ),
        migrations.AddIndex(
            model_name='finca',
            index=models.Index(fields=['agricultor', '-created_at'], name='api_finca_agricultor_created_idx'),
        ),
        migrations.AddIndex(
            model_name='finca',
            index=models.Index(fields=['municipio', 'departamento'], name='api_finca_municipio_departamento_idx'),
        ),
        migrations.AddIndex(
            model_name='finca',
            index=models.Index(fields=['activa'], name='api_finca_activa_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['finca', '-created_at'], name='api_lote_finca_created_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['variedad'], name='api_lote_variedad_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['estado'], name='api_lote_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['activo'], name='api_lote_activo_idx'),
        ),
        migrations.AddConstraint(
            model_name='finca',
            constraint=models.CheckConstraint(check=models.Q(('hectareas__gt', 0)), name='finca_hectareas_positivas'),
        ),
        migrations.AddConstraint(
            model_name='lote',
            constraint=models.CheckConstraint(check=models.Q(('area_hectareas__gt', 0)), name='lote_area_positiva'),
        ),
        migrations.AddConstraint(
            model_name='lote',
            constraint=models.CheckConstraint(check=models.Q(('fecha_cosecha__isnull', True), ('fecha_cosecha__gte', models.F('fecha_plantacion'))), name='lote_fecha_cosecha_valida'),
        ),
        migrations.AddConstraint(
            model_name='lote',
            constraint=models.UniqueConstraint(fields=('finca', 'identificador'), name='lote_identificador_unico_por_finca'),
        ),
    ]
