# Generated by Django 4.2.7 on 2025-10-24 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_fincas_lotes_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpiringToken',
        ),
    ]
