# Generated by Django 4.2.7 on 2025-10-24 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_expiring_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cacaoimage',
            name='lote_id',
        ),
        migrations.AddField(
            model_name='cacaoimage',
            name='lote',
            field=models.ForeignKey(blank=True, help_text='Lote al que pertenece esta imagen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cacao_images', to='api.lote'),
        ),
    ]


