# Generated by Django 4.2.7 on 2025-10-24 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_fix_lote_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión'), ('create', 'Creación'), ('update', 'Actualización'), ('delete', 'Eliminación'), ('view', 'Visualización'), ('download', 'Descarga'), ('upload', 'Subida'), ('analysis', 'Análisis'), ('training', 'Entrenamiento'), ('report', 'Reporte'), ('error', 'Error')], help_text='Tipo de acción realizada', max_length=20)),
                ('modelo', models.CharField(help_text='Modelo afectado (ej: CacaoImage, Finca)', max_length=50)),
                ('objeto_id', models.CharField(blank=True, help_text='ID del objeto afectado', max_length=100, null=True)),
                ('descripcion', models.TextField(help_text='Descripción detallada de la acción')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP del usuario', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User Agent del navegador', null=True)),
                ('datos_antes', models.JSONField(blank=True, default=dict, help_text='Estado del objeto antes de la acción')),
                ('datos_despues', models.JSONField(blank=True, default=dict, help_text='Estado del objeto después de la acción')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la acción')),
            ],
            options={
                'verbose_name': 'Log de Actividad',
                'verbose_name_plural': 'Logs de Actividad',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='Dirección IP del usuario')),
                ('user_agent', models.TextField(help_text='User Agent del navegador')),
                ('login_time', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del inicio de sesión')),
                ('logout_time', models.DateTimeField(blank=True, help_text='Fecha y hora del cierre de sesión', null=True)),
                ('session_duration', models.DurationField(blank=True, help_text='Duración de la sesión', null=True)),
                ('success', models.BooleanField(default=True, help_text='Indica si el inicio de sesión fue exitoso')),
                ('failure_reason', models.CharField(blank=True, help_text='Razón del fallo si no fue exitoso', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Historial de Login',
                'verbose_name_plural': 'Historial de Logins',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='ModelMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='Nombre del modelo', max_length=100)),
                ('model_type', models.CharField(choices=[('regression', 'Modelo de Regresión'), ('classification', 'Modelo de Clasificación'), ('segmentation', 'Modelo de Segmentación'), ('incremental', 'Modelo Incremental')], max_length=20)),
                ('target', models.CharField(choices=[('alto', 'Altura'), ('ancho', 'Ancho'), ('grosor', 'Grosor'), ('peso', 'Peso'), ('calidad', 'Calidad'), ('variedad', 'Variedad')], help_text='Variable objetivo', max_length=20)),
                ('version', models.CharField(help_text='Versión del modelo', max_length=20)),
                ('metric_type', models.CharField(choices=[('training', 'Métricas de Entrenamiento'), ('validation', 'Métricas de Validación'), ('test', 'Métricas de Prueba'), ('incremental', 'Métricas Incrementales')], max_length=20)),
                ('mae', models.FloatField(help_text='Mean Absolute Error')),
                ('mse', models.FloatField(help_text='Mean Squared Error')),
                ('rmse', models.FloatField(help_text='Root Mean Squared Error')),
                ('r2_score', models.FloatField(help_text='R² Score')),
                ('mape', models.FloatField(blank=True, help_text='Mean Absolute Percentage Error', null=True)),
                ('additional_metrics', models.JSONField(default=dict, help_text='Métricas adicionales específicas del modelo')),
                ('dataset_size', models.PositiveIntegerField(help_text='Tamaño del dataset usado')),
                ('train_size', models.PositiveIntegerField(help_text='Tamaño del conjunto de entrenamiento')),
                ('validation_size', models.PositiveIntegerField(help_text='Tamaño del conjunto de validación')),
                ('test_size', models.PositiveIntegerField(help_text='Tamaño del conjunto de prueba')),
                ('epochs', models.PositiveIntegerField(help_text='Número de épocas de entrenamiento')),
                ('batch_size', models.PositiveIntegerField(help_text='Tamaño del batch')),
                ('learning_rate', models.FloatField(help_text='Tasa de aprendizaje')),
                ('model_params', models.JSONField(default=dict, help_text='Parámetros específicos del modelo')),
                ('training_time_seconds', models.PositiveIntegerField(blank=True, help_text='Tiempo de entrenamiento en segundos', null=True)),
                ('inference_time_ms', models.FloatField(blank=True, help_text='Tiempo de inferencia promedio en milisegundos', null=True)),
                ('stability_score', models.FloatField(blank=True, help_text='Puntuación de estabilidad del modelo', null=True)),
                ('knowledge_retention', models.FloatField(blank=True, help_text='Porcentaje de retención de conocimiento', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el modelo')),
                ('is_best_model', models.BooleanField(default=False, help_text='Indica si es el mejor modelo')),
                ('is_production_model', models.BooleanField(default=False, help_text='Indica si está en producción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Métricas de Modelo',
                'verbose_name_plural': 'Métricas de Modelos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('error', 'Error'), ('success', 'Éxito'), ('defect_alert', 'Alerta de Defecto'), ('report_ready', 'Reporte Listo'), ('training_complete', 'Entrenamiento Completo'), ('welcome', 'Bienvenida')], help_text='Tipo de notificación', max_length=20)),
                ('titulo', models.CharField(help_text='Título de la notificación', max_length=200)),
                ('mensaje', models.TextField(help_text='Mensaje detallado de la notificación')),
                ('leida', models.BooleanField(default=False, help_text='Indica si la notificación ha sido leída')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la notificación')),
                ('fecha_lectura', models.DateTimeField(blank=True, help_text='Fecha en que se marcó como leída', null=True)),
                ('datos_extra', models.JSONField(blank=True, default=dict, help_text='Datos adicionales en formato JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(choices=[('calidad', 'Reporte de Calidad'), ('defectos', 'Reporte de Defectos'), ('rendimiento', 'Reporte de Rendimiento'), ('finca', 'Reporte de Finca'), ('lote', 'Reporte de Lote'), ('usuario', 'Reporte de Usuario'), ('auditoria', 'Reporte de Auditoría'), ('personalizado', 'Reporte Personalizado')], help_text='Tipo de reporte generado', max_length=20)),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], help_text='Formato del reporte', max_length=10)),
                ('titulo', models.CharField(help_text='Título del reporte', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del reporte', null=True)),
                ('estado', models.CharField(choices=[('generando', 'Generando'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('expirado', 'Expirado')], default='generando', help_text='Estado actual del reporte', max_length=20)),
                ('archivo', models.FileField(blank=True, help_text='Archivo del reporte generado', null=True, upload_to='reportes/%Y/%m/%d/')),
                ('nombre_archivo', models.CharField(blank=True, help_text='Nombre del archivo generado', max_length=255, null=True)),
                ('tamaño_archivo', models.PositiveIntegerField(blank=True, help_text='Tamaño del archivo en bytes', null=True)),
                ('parametros', models.JSONField(blank=True, default=dict, help_text='Parámetros utilizados para generar el reporte')),
                ('filtros_aplicados', models.JSONField(blank=True, default=dict, help_text='Filtros aplicados al generar el reporte')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, help_text='Fecha de solicitud del reporte')),
                ('fecha_generacion', models.DateTimeField(blank=True, help_text='Fecha de generación del reporte', null=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, help_text='Fecha de expiración del reporte', null=True)),
                ('tiempo_generacion', models.DurationField(blank=True, help_text='Tiempo que tardó en generarse', null=True)),
                ('mensaje_error', models.TextField(blank=True, help_text='Mensaje de error si falló la generación', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reporte Generado',
                'verbose_name_plural': 'Reportes Generados',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='lote',
            name='lote_fecha_cosecha_valida',
        ),
        migrations.RenameIndex(
            model_name='cacaoimage',
            new_name='api_cacaoim_user_id_ebd169_idx',
            old_name='api_cacaoim_user_id_created_idx',
        ),
        migrations.RenameIndex(
            model_name='cacaoimage',
            new_name='api_cacaoim_process_347fb4_idx',
            old_name='api_cacaoim_processed_idx',
        ),
        migrations.RenameIndex(
            model_name='cacaoimage',
            new_name='api_cacaoim_region_4e28a0_idx',
            old_name='api_cacaoim_region_finca_idx',
        ),
        migrations.RenameIndex(
            model_name='cacaoprediction',
            new_name='api_cacaopr_image_i_9635eb_idx',
            old_name='api_cacaopr_image_id_idx',
        ),
        migrations.RenameIndex(
            model_name='cacaoprediction',
            new_name='api_cacaopr_created_d7f6bb_idx',
            old_name='api_cacaopr_created_idx',
        ),
        migrations.RenameIndex(
            model_name='cacaoprediction',
            new_name='api_cacaopr_model_v_b99086_idx',
            old_name='api_cacaopr_model_version_idx',
        ),
        migrations.RenameIndex(
            model_name='finca',
            new_name='api_finca_agricul_f9cee8_idx',
            old_name='api_finca_agricultor_created_idx',
        ),
        migrations.RenameIndex(
            model_name='finca',
            new_name='api_finca_municip_582e68_idx',
            old_name='api_finca_municipio_departamento_idx',
        ),
        migrations.RenameIndex(
            model_name='finca',
            new_name='api_finca_activa_44817f_idx',
            old_name='api_finca_activa_idx',
        ),
        migrations.RenameIndex(
            model_name='lote',
            new_name='api_lote_finca_i_9482d1_idx',
            old_name='api_lote_finca_created_idx',
        ),
        migrations.RenameIndex(
            model_name='lote',
            new_name='api_lote_varieda_bd3734_idx',
            old_name='api_lote_variedad_idx',
        ),
        migrations.RenameIndex(
            model_name='lote',
            new_name='api_lote_estado_4f08df_idx',
            old_name='api_lote_estado_idx',
        ),
        migrations.RenameIndex(
            model_name='lote',
            new_name='api_lote_activo_151304_idx',
            old_name='api_lote_activo_idx',
        ),
        migrations.RenameIndex(
            model_name='trainingjob',
            new_name='api_trainin_status_8cb80f_idx',
            old_name='api_trainin_status_8b2b0b_idx',
        ),
        migrations.RenameIndex(
            model_name='trainingjob',
            new_name='api_trainin_job_typ_e52bad_idx',
            old_name='api_trainin_job_typ_3a8b0b_idx',
        ),
        migrations.RenameIndex(
            model_name='trainingjob',
            new_name='api_trainin_created_65d9c4_idx',
            old_name='api_trainin_created_8b2b0b_idx',
        ),
        migrations.AddConstraint(
            model_name='lote',
            constraint=models.CheckConstraint(check=models.Q(('fecha_cosecha__isnull', True), ('fecha_cosecha__gte', models.F('fecha_plantacion')), _connector='OR'), name='lote_fecha_cosecha_valida'),
        ),
        migrations.AddField(
            model_name='reportegenerado',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario que solicitó el reporte', on_delete=django.db.models.deletion.CASCADE, related_name='reportes_generados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(help_text='Usuario destinatario de la notificación', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelmetrics',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelmetrics',
            name='training_job',
            field=models.ForeignKey(blank=True, help_text='Trabajo de entrenamiento asociado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_metrics', to='api.trainingjob'),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario que inició sesión', on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='reportegenerado',
            index=models.Index(fields=['usuario', '-fecha_solicitud'], name='api_reporte_usuario_631114_idx'),
        ),
        migrations.AddIndex(
            model_name='reportegenerado',
            index=models.Index(fields=['tipo_reporte', '-fecha_solicitud'], name='api_reporte_tipo_re_ac3fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='reportegenerado',
            index=models.Index(fields=['estado'], name='api_reporte_estado_c21744_idx'),
        ),
        migrations.AddIndex(
            model_name='reportegenerado',
            index=models.Index(fields=['formato'], name='api_reporte_formato_55d2b8_idx'),
        ),
        migrations.AddIndex(
            model_name='reportegenerado',
            index=models.Index(fields=['fecha_solicitud'], name='api_reporte_fecha_s_91879e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-fecha_creacion'], name='api_notific_user_id_ac17e4_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['leida'], name='api_notific_leida_a29a67_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tipo'], name='api_notific_tipo_592f5e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['fecha_creacion'], name='api_notific_fecha_c_bd998a_idx'),
        ),
        migrations.AddIndex(
            model_name='modelmetrics',
            index=models.Index(fields=['model_name', 'version'], name='api_modelme_model_n_617b8b_idx'),
        ),
        migrations.AddIndex(
            model_name='modelmetrics',
            index=models.Index(fields=['model_type', 'target'], name='api_modelme_model_t_9928c0_idx'),
        ),
        migrations.AddIndex(
            model_name='modelmetrics',
            index=models.Index(fields=['metric_type'], name='api_modelme_metric__74fb4f_idx'),
        ),
        migrations.AddIndex(
            model_name='modelmetrics',
            index=models.Index(fields=['created_by', '-created_at'], name='api_modelme_created_5e9c32_idx'),
        ),
        migrations.AddIndex(
            model_name='modelmetrics',
            index=models.Index(fields=['is_best_model'], name='api_modelme_is_best_730ec5_idx'),
        ),
        migrations.AddIndex(
            model_name='modelmetrics',
            index=models.Index(fields=['is_production_model'], name='api_modelme_is_prod_fa489d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='modelmetrics',
            unique_together={('model_name', 'version', 'metric_type', 'target')},
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['usuario', '-login_time'], name='api_loginhi_usuario_19e442_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['ip_address'], name='api_loginhi_ip_addr_8a6a17_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['login_time'], name='api_loginhi_login_t_04aef5_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['success'], name='api_loginhi_success_78b423_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['usuario', '-timestamp'], name='api_activit_usuario_c881c3_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['accion', '-timestamp'], name='api_activit_accion_587fa6_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['modelo', '-timestamp'], name='api_activit_modelo_e04f60_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['timestamp'], name='api_activit_timesta_dffb43_idx'),
        ),
    ]
