# Generated by Django 4.2.7 on 2025-10-26 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_agricultor_id_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='finca',
            new_name='api_finca_agricul_8d1606_idx',
            old_name='api_finca_agricultor_id_idx',
        ),
    ]


