# Generated by Django 4.2.7 on 2025-10-28 21:57
# -*- coding: utf-8 -*-

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_api_finca_agricultor_id_idx_api_finca_agricul_8d1606_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sistema', models.CharField(default='CacaoScan', help_text='Nombre del sistema', max_length=100)),
                ('email_contacto', models.EmailField(default='contacto@cacaoscan.com', help_text='Correo de contacto principal', max_length=254)),
                ('lema', models.CharField(default='La mejor plataforma para el control de calidad del cacao', help_text='Lema o descripción del sistema', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Logo del sistema', null=True, upload_to='system_settings/')),
                ('recaptcha_enabled', models.BooleanField(default=True, help_text='Activar reCAPTCHA')),
                ('session_timeout', models.IntegerField(default=60, help_text='Tiempo de sesión en minutos')),
                ('login_attempts', models.IntegerField(default=5, help_text='Número máximo de intentos de login')),
                ('two_factor_auth', models.BooleanField(default=False, help_text='Activar autenticación de dos factores')),
                ('active_model', models.CharField(default='yolov8', help_text='Modelo activo para predicciones', max_length=50)),
                ('last_training', models.DateTimeField(blank=True, help_text='Fecha de último entrenamiento', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
                'ordering': ['-updated_at'],
            },
        ),
    ]


