# Generated by Django 4.2.7 on 2025-10-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_finca_finca_hectareas_positivas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cacaoimage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
