# Generated by Django 4.2.7 on 2025-11-25 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_moved_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='cacaoimage',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='cacaoimage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cacaoprediction',
            name='image',
        ),
        migrations.RemoveField(
            model_name='emailverificationtoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='finca',
            name='agricultor',
        ),
        migrations.RemoveField(
            model_name='loginhistory',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='finca',
        ),
        migrations.AlterUniqueTogether(
            name='modelmetrics',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='modelmetrics',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='modelmetrics',
            name='training_job',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reportegenerado',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='SystemSettings',
        ),
        migrations.RemoveField(
            model_name='trainingjob',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='CacaoImage',
        ),
        migrations.DeleteModel(
            name='CacaoPrediction',
        ),
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
        migrations.DeleteModel(
            name='Finca',
        ),
        migrations.DeleteModel(
            name='LoginHistory',
        ),
        migrations.DeleteModel(
            name='Lote',
        ),
        migrations.DeleteModel(
            name='ModelMetrics',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='ReporteGenerado',
        ),
        migrations.DeleteModel(
            name='TrainingJob',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
