# Generated by Django 5.2.8 on 2025-12-01 17:24
# -*- coding: utf-8 -*-

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_fix_fecha_generacion_non_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportegenerado',
            name='ruta_archivo',
            field=models.CharField(blank=True, default='', help_text='Ruta del archivo generado', max_length=500),
        ),
        migrations.AlterField(
            model_name='reportegenerado',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('generando', 'Generando'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('expirado', 'Expirado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportegenerado',
            name='formato',
            field=models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], default='pdf', max_length=10),
        ),
        migrations.AlterField(
            model_name='reportegenerado',
            name='tipo_reporte',
            field=models.CharField(choices=[('calidad', 'Reporte de Calidad'), ('defectos', 'Reporte de Defectos'), ('rendimiento', 'Reporte de Rendimiento'), ('finca', 'Reporte de Finca'), ('lote', 'Reporte de Lote'), ('usuario', 'Reporte de Usuario'), ('auditoria', 'Reporte de Auditoría'), ('personalizado', 'Reporte Personalizado'), ('analisis_periodo', 'Análisis por Período')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reportegenerado',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
