# Generated by Django 5.2.8 on 2025-12-01 13:26
# -*- coding: utf-8 -*-

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('error', 'Error'), ('success', 'Éxito'), ('defect_alert', 'Alerta de Defecto'), ('report_ready', 'Reporte Listo'), ('training_complete', 'Entrenamiento Completo'), ('welcome', 'Bienvenida')], default='info', help_text='Tipo de notificación', max_length=20)),
                ('titulo', models.CharField(help_text='Título de la notificación', max_length=200)),
                ('mensaje', models.TextField(help_text='Mensaje detallado de la notificación')),
                ('leida', models.BooleanField(default=False, help_text='Indica si la notificación ha sido leída')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la notificación')),
                ('fecha_lectura', models.DateTimeField(blank=True, help_text='Fecha en que se marcó como leída', null=True)),
                ('datos_extra', models.JSONField(blank=True, default=dict, help_text='Datos adicionales en formato JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Usuario destinatario de la notificación', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['user', '-fecha_creacion'], name='notificatio_user_id_07ce85_idx'), models.Index(fields=['leida', '-fecha_creacion'], name='notificatio_leida_c18052_idx')],
            },
        ),
    ]
