# Generated by Django 5.2.8 on 2025-12-01 17:24
# -*- coding: utf-8 -*-

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_fix_non_nullable_fields_temporary_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='mensaje',
            field=models.TextField(help_text='Mensaje detallado de la notificación'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='titulo',
            field=models.CharField(help_text='Título de la notificación', max_length=200),
        ),
    ]
