sonar.projectKey=cacao-scan
sonar.sources=.
sonar.host.url=https://sonarqube.dataguaviare.com.co
sonar.token=sqa_6c7962b13c154048dec724ba7c8f559ed489f89d
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/vendor/**,**/node_modules/**,**/storage/**,**/bootstrap/cache/**,**/public/build/**,**/public/vendor/**,**/public/dist/**