# Generated by Django 4.2.7 on 2025-10-31 09:58
# -*- coding: utf-8 -*-

from django.db import migrations, models, connection


def _rename_table_if_needed_forward(apps, schema_editor):
    """Rename table if needed (forward, compatible with SQLite and PostgreSQL)."""
    db_engine = connection.settings_dict.get('ENGINE', '')
    
    with connection.cursor() as cursor:
        if 'postgresql' in db_engine:
            # Check if old table exists and new doesn't
            cursor.execute("""
                SELECT 1 FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'fincas_app_finca'
            """)
            old_exists = cursor.fetchone()
            
            cursor.execute("""
                SELECT 1 FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'api_finca'
            """)
            new_exists = cursor.fetchone()
            
            if old_exists and not new_exists:
                cursor.execute('ALTER TABLE fincas_app_finca RENAME TO api_finca')
        # For SQLite, Django will handle the table rename through state operations


def _rename_table_if_needed_reverse(apps, schema_editor):
    """Rename table if needed (reverse, compatible with SQLite and PostgreSQL)."""
    db_engine = connection.settings_dict.get('ENGINE', '')
    
    with connection.cursor() as cursor:
        if 'postgresql' in db_engine:
            # Reverse: rename back
            cursor.execute("""
                SELECT 1 FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'api_finca'
            """)
            new_exists = cursor.fetchone()
            
            cursor.execute("""
                SELECT 1 FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'fincas_app_finca'
            """)
            old_exists = cursor.fetchone()
            
            if new_exists and not old_exists:
                cursor.execute('ALTER TABLE api_finca RENAME TO fincas_app_finca')
        # For SQLite, Django will handle the table rename through state operations


def rename_indexes_if_exist(apps, schema_editor):
    """
    Renombra índices solo si existen. Si no existen, los crea directamente con los nombres correctos.
    """
    db_alias = schema_editor.connection.alias
    connection = schema_editor.connection
    
    with connection.cursor() as cursor:
        # Lista de índices a renombrar/crear
        index_mappings = [
            {
                'old_name': 'fincas_app__agricul_396b5b_idx',
                'new_name': 'api_finca_agricul_f9cee8_idx',
            },
            {
                'old_name': 'fincas_app__agricul_ef7f1d_idx',
                'new_name': 'api_finca_agricul_8d1606_idx',
            },
            {
                'old_name': 'fincas_app__municip_636180_idx',
                'new_name': 'api_finca_municip_582e68_idx',
            },
            {
                'old_name': 'fincas_app__activa_cf04c9_idx',
                'new_name': 'api_finca_activa_44817f_idx',
            },
        ]
        
        # Verificar existencia de índices antiguos y renombrarlos
        for index_map in index_mappings:
            # Verificar si el índice antiguo existe
            cursor.execute("""
                SELECT 1 FROM pg_indexes 
                WHERE tablename = 'api_finca' 
                AND indexname = %s
            """, [index_map['old_name']])
            
            old_exists = cursor.fetchone()
            
            # Verificar si el índice nuevo ya existe
            cursor.execute("""
                SELECT 1 FROM pg_indexes 
                WHERE tablename = 'api_finca' 
                AND indexname = %s
            """, [index_map['new_name']])
            
            new_exists = cursor.fetchone()
            
            if old_exists and not new_exists:
                # Renombrar el índice existente
                old_name = index_map['old_name']
                new_name = index_map['new_name']
                cursor.execute(
                    f'ALTER INDEX "{old_name}" RENAME TO "{new_name}"'
                )


def reverse_rename_indexes(apps, schema_editor):
    """
    Revierte los cambios de índices.
    """
    db_alias = schema_editor.connection.alias
    connection = schema_editor.connection
    
    with connection.cursor() as cursor:
        index_mappings = [
            ('api_finca_agricul_f9cee8_idx', 'fincas_app__agricul_396b5b_idx'),
            ('api_finca_agricul_8d1606_idx', 'fincas_app__agricul_ef7f1d_idx'),
            ('api_finca_municip_582e68_idx', 'fincas_app__municip_636180_idx'),
            ('api_finca_activa_44817f_idx', 'fincas_app__activa_cf04c9_idx'),
        ]
        
        for new_name, old_name in index_mappings:
            cursor.execute("""
                SELECT 1 FROM pg_indexes 
                WHERE tablename = 'api_finca' 
                AND indexname = %s
            """, [new_name])
            
            if cursor.fetchone():
                cursor.execute(
                    f'ALTER INDEX "{new_name}" RENAME TO "{old_name}"'
                )


class Migration(migrations.Migration):

    dependencies = [
        ('fincas_app', '0002_link_to_api_finca'),
    ]

    operations = [
        # Verificar y renombrar tabla solo si existe con el nombre antiguo
        migrations.RunPython(
            _rename_table_if_needed_forward,
            _rename_table_if_needed_reverse
        ),
        # Renombrar índices de manera segura
        migrations.RunPython(rename_indexes_if_exist, reverse_rename_indexes),
        # Actualizar el estado interno de Django sin hacer cambios en la BD
        # Ya que la tabla api_finca existe, solo necesitamos registrar el cambio
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # No hacer nada en la base de datos
                migrations.RunSQL("SELECT 1;", reverse_sql="SELECT 1;"),
            ],
            state_operations=[
                # Actualizar el estado interno de Django
                migrations.AlterModelTable(
                    name='finca',
                    table='api_finca',
                ),
            ],
        ),
        # Crear índices que no existen (usando el nombre correcto directamente)
        migrations.RunSQL(
            sql="""
                -- Crear índice si no existe
                CREATE INDEX IF NOT EXISTS api_finca_agricul_f9cee8_idx 
                ON api_finca (agricultor_id, created_at DESC);
                
                CREATE INDEX IF NOT EXISTS api_finca_agricul_8d1606_idx 
                ON api_finca (agricultor_id);
                
                CREATE INDEX IF NOT EXISTS api_finca_municip_582e68_idx 
                ON api_finca (municipio, departamento);
                
                CREATE INDEX IF NOT EXISTS api_finca_activa_44817f_idx 
                ON api_finca (activa);
            """,
            reverse_sql="""
                -- No necesitamos revertir estos índices ya que pueden seguir siendo útiles
                -- DROP INDEX IF EXISTS api_finca_agricul_f9cee8_idx;
                -- DROP INDEX IF EXISTS api_finca_agricul_8d1606_idx;
                -- DROP INDEX IF EXISTS api_finca_municip_582e68_idx;
                -- DROP INDEX IF EXISTS api_finca_activa_44817f_idx;
            """
        ),
    ]
