# Generated by Django 4.2.7 on 2025-11-25 14:22
# -*- coding: utf-8 -*-
# Note: Index renaming is handled by migration 0003, this migration is kept for state tracking only

from django.db import migrations


def rename_indexes_if_exist(apps, schema_editor):
    """
    Renombra índices solo si existen. Esta migración es redundante
    ya que la migración 0003 ya maneja el renombrado de índices.
    """
    connection = schema_editor.connection
    
    with connection.cursor() as cursor:
        index_mappings = [
            ('fincas_app__agricul_396b5b_idx', 'api_finca_agricul_f9cee8_idx'),
            ('fincas_app__agricul_ef7f1d_idx', 'api_finca_agricul_8d1606_idx'),
            ('fincas_app__municip_636180_idx', 'api_finca_municip_582e68_idx'),
            ('fincas_app__activa_cf04c9_idx', 'api_finca_activa_44817f_idx'),
        ]
        
        for old_name, new_name in index_mappings:
            # Check if old index exists and new doesn't
            cursor.execute("""
                SELECT 1 FROM pg_indexes 
                WHERE tablename = 'api_finca' 
                AND indexname = %s
            """, [old_name])
            
            old_exists = cursor.fetchone()
            
            cursor.execute("""
                SELECT 1 FROM pg_indexes 
                WHERE tablename = 'api_finca' 
                AND indexname = %s
            """, [new_name])
            
            new_exists = cursor.fetchone()
            
            if old_exists and not new_exists:
                cursor.execute(f'ALTER INDEX "{old_name}" RENAME TO "{new_name}"')


def reverse_rename_indexes(apps, schema_editor):
    """Reverse operation - not typically needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('fincas_app', '0004_fix_lote_foreign_key'),
    ]

    operations = [
        # Use SeparateDatabaseAndState to only update Django's state
        # Index renaming was already handled by migration 0003
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name='finca',
                    new_name='api_finca_agricul_f9cee8_idx',
                    old_name='fincas_app__agricul_396b5b_idx',
                ),
                migrations.RenameIndex(
                    model_name='finca',
                    new_name='api_finca_agricul_8d1606_idx',
                    old_name='fincas_app__agricul_ef7f1d_idx',
                ),
                migrations.RenameIndex(
                    model_name='finca',
                    new_name='api_finca_municip_582e68_idx',
                    old_name='fincas_app__municip_636180_idx',
                ),
                migrations.RenameIndex(
                    model_name='finca',
                    new_name='api_finca_activa_44817f_idx',
                    old_name='fincas_app__activa_cf04c9_idx',
                ),
            ],
            database_operations=[
                # Index renaming was already handled by migration 0003
                # Only update Django's state, don't modify the database
                migrations.RunSQL("SELECT 1;", reverse_sql="SELECT 1;"),
            ],
        ),
    ]
