# Generated by Django 4.2.7 on 2025-11-25 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fincas_app', '0004_fix_lote_foreign_key'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='finca',
            new_name='api_finca_agricul_f9cee8_idx',
            old_name='fincas_app__agricul_396b5b_idx',
        ),
        migrations.RenameIndex(
            model_name='finca',
            new_name='api_finca_agricul_8d1606_idx',
            old_name='fincas_app__agricul_ef7f1d_idx',
        ),
        migrations.RenameIndex(
            model_name='finca',
            new_name='api_finca_municip_582e68_idx',
            old_name='fincas_app__municip_636180_idx',
        ),
        migrations.RenameIndex(
            model_name='finca',
            new_name='api_finca_activa_44817f_idx',
            old_name='fincas_app__activa_cf04c9_idx',
        ),
    ]
