# Generated by Django 5.2.8 on 2025-12-01 17:24
# -*- coding: utf-8 -*-

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fincas_app', '0009_fix_non_nullable_fields_temporary_defaults'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lote',
            name='fincas_app_lote_identificador_unico_por_finca',
        ),
        migrations.AlterField(
            model_name='finca',
            name='departamento',
            field=models.CharField(help_text='Departamento donde se encuentra la finca', max_length=100),
        ),
        migrations.AlterField(
            model_name='finca',
            name='hectareas',
            field=models.DecimalField(decimal_places=2, help_text='Área total de la finca en hectáreas', max_digits=10),
        ),
        migrations.AlterField(
            model_name='finca',
            name='municipio',
            field=models.CharField(help_text='Municipio donde se encuentra la finca', max_length=100),
        ),
        migrations.AlterField(
            model_name='finca',
            name='nombre',
            field=models.CharField(help_text='Nombre de la finca', max_length=200),
        ),
        migrations.AlterField(
            model_name='finca',
            name='ubicacion',
            field=models.CharField(help_text='Dirección o ubicación de la finca', max_length=300),
        ),
        migrations.AlterField(
            model_name='lote',
            name='area_hectareas',
            field=models.DecimalField(decimal_places=2, help_text='Área del lote en hectáreas', max_digits=8),
        ),
        migrations.AlterField(
            model_name='lote',
            name='finca',
            field=models.ForeignKey(help_text='Finca a la que pertenece el lote', on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='fincas_app.finca'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='identificador',
            field=models.CharField(blank=True, default='', help_text='Identificador único del lote dentro de la finca', max_length=50),
        ),
        migrations.AlterField(
            model_name='lote',
            name='nombre',
            field=models.CharField(help_text='Nombre del lote', max_length=200),
        ),
        migrations.AlterField(
            model_name='lote',
            name='variedad',
            field=models.CharField(help_text='Variedad de cacao del lote', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='lote',
            constraint=models.UniqueConstraint(condition=models.Q(('identificador__gt', '')), fields=('finca', 'identificador'), name='fincas_app_lote_identificador_unico_por_finca'),
        ),
    ]
