# Generated by Django 5.2.9 on 2025-12-09 16:00
# Modified: Added data migration to convert municipio from CharField to ForeignKey

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_municipio_data(apps, schema_editor):
    """
    Migrate municipio from CharField to ForeignKey.
    Converts municipio/departamento text values to municipio_id (FK).
    """
    Finca = apps.get_model('fincas_app', 'Finca')
    Municipio = apps.get_model('catalogos', 'Municipio')
    
    with schema_editor.connection.cursor() as cursor:
        # Check if municipio_id already exists and has data
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_schema = 'public' 
            AND table_name = 'api_finca'
            AND column_name = 'municipio_id'
        """)
        municipio_id_exists = cursor.fetchone() is not None
        
        if municipio_id_exists:
            cursor.execute("SELECT COUNT(*) FROM api_finca WHERE municipio_id IS NOT NULL")
            existing_count = cursor.fetchone()[0]
            if existing_count > 0:
                print(f"municipio_id already exists with {existing_count} non-null values, skipping data migration")
                return
        
        # Check if municipio column exists and is text type
        cursor.execute("""
            SELECT column_name, data_type 
            FROM information_schema.columns 
            WHERE table_schema = 'public' 
            AND table_name = 'api_finca'
            AND column_name = 'municipio'
        """)
        municipio_col = cursor.fetchone()
        
        if not municipio_col:
            print("Column 'municipio' does not exist, skipping data migration")
            return
        
        if municipio_col[1] != 'character varying':
            print(f"Column 'municipio' is not text type ({municipio_col[1]}), skipping data migration")
            return
        
        # Check if departamento column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_schema = 'public' 
            AND table_name = 'api_finca'
            AND column_name = 'departamento'
        """)
        has_departamento = cursor.fetchone() is not None
        
        # Get all fincas with municipio as text
        if has_departamento:
            cursor.execute("""
                SELECT id, municipio, departamento 
                FROM api_finca 
                WHERE municipio IS NOT NULL 
                AND municipio NOT SIMILAR TO '[0-9]+'
            """)
        else:
            cursor.execute("""
                SELECT id, municipio, NULL as departamento 
                FROM api_finca 
                WHERE municipio IS NOT NULL 
                AND municipio NOT SIMILAR TO '[0-9]+'
            """)
        
        fincas = cursor.fetchall()
        migrated = 0
        not_found = 0
        errors = 0
        
        for finca_id, municipio_text, departamento_text in fincas:
            try:
                municipio_id = None
                
                # Try to find municipio by name and departamento (case insensitive)
                if municipio_text and departamento_text:
                    cursor.execute("""
                        SELECT m.id 
                        FROM catalogos_municipio m
                        JOIN catalogos_departamento d ON m.departamento_id = d.id
                        WHERE LOWER(m.nombre) = LOWER(%s)
                        AND LOWER(d.nombre) = LOWER(%s)
                        LIMIT 1
                    """, [municipio_text.strip(), departamento_text.strip()])
                    result = cursor.fetchone()
                    if result:
                        municipio_id = result[0]
                
                # If not found, try by municipio name only
                if not municipio_id and municipio_text:
                    cursor.execute("""
                        SELECT id FROM catalogos_municipio 
                        WHERE LOWER(nombre) = LOWER(%s)
                        LIMIT 1
                    """, [municipio_text.strip()])
                    result = cursor.fetchone()
                    if result:
                        municipio_id = result[0]
                
                # Update finca with municipio_id
                if municipio_id:
                    cursor.execute("""
                        UPDATE api_finca 
                        SET municipio_id = %s 
                        WHERE id = %s
                    """, [municipio_id, finca_id])
                    migrated += 1
                else:
                    not_found += 1
                    print(f"Warning: No municipio found for '{municipio_text}', '{departamento_text}' (Finca ID: {finca_id})")
                    
            except Exception as e:
                errors += 1
                print(f"Error migrating Finca ID {finca_id}: {e}")
        
        print(f"Migrated {migrated} fincas, {not_found} not found, {errors} errors")
        
        # Check if there are any fincas with NULL municipio_id
        cursor.execute("""
            SELECT COUNT(*) FROM api_finca WHERE municipio_id IS NULL
        """)
        null_count = cursor.fetchone()[0]
        
        if null_count > 0:
            raise ValueError(
                f"Cannot proceed: {null_count} fincas have NULL municipio_id. "
                f"Please fix the data before running this migration. "
                f"Check the warnings above for details."
            )


def reverse_migrate_municipio_data(apps, schema_editor):
    """
    Reverse migration: convert municipio_id back to municipio text.
    This is a one-way migration in practice, but we provide a reverse for completeness.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_add_string_defaults'),
        ('fincas_app', '0010_remove_lote_fincas_app_lote_identificador_unico_por_finca_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='finca',
            name='api_finca_municip_582e68_idx',
        ),
        # Step 1: Add municipio_id column (temporary, nullable, without FK constraint for now)
        migrations.RunSQL(
            sql="""
                ALTER TABLE api_finca 
                ADD COLUMN IF NOT EXISTS municipio_id BIGINT NULL;
            """,
            reverse_sql="ALTER TABLE api_finca DROP COLUMN IF EXISTS municipio_id;"
        ),
        # Step 2: Migrate data from municipio (text) to municipio_id (FK)
        migrations.RunPython(
            migrate_municipio_data,
            reverse_migrate_municipio_data,
        ),
        # Step 3: Remove departamento field (no longer needed, comes from municipio.departamento)
        # Use RunSQL to safely remove the column if it exists
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT FROM information_schema.columns 
                        WHERE table_schema = 'public' 
                        AND table_name = 'api_finca'
                        AND column_name = 'departamento'
                    ) THEN
                        ALTER TABLE api_finca DROP COLUMN departamento;
                    END IF;
                END $$;
            """,
            reverse_sql="-- Reverse: departamento column cannot be restored"
        ),
        # Step 4: Update Django state to remove departamento field
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='finca',
                    name='departamento',
                ),
            ],
            database_operations=[],
        ),
        # Step 5: Drop old municipio column (CharField)
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT FROM information_schema.columns 
                        WHERE table_schema = 'public' 
                        AND table_name = 'api_finca'
                        AND column_name = 'municipio'
                        AND data_type = 'character varying'
                    ) THEN
                        ALTER TABLE api_finca DROP COLUMN municipio;
                    END IF;
                END $$;
            """,
            reverse_sql="""
                ALTER TABLE api_finca 
                ADD COLUMN municipio VARCHAR(100);
            """
        ),
        # Step 6: Make municipio_id NOT NULL (after data migration)
        migrations.RunSQL(
            sql="""
                ALTER TABLE api_finca 
                ALTER COLUMN municipio_id SET NOT NULL;
            """,
            reverse_sql="""
                ALTER TABLE api_finca 
                ALTER COLUMN municipio_id DROP NOT NULL;
            """
        ),
        # Step 7: Add foreign key constraint
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint 
                        WHERE conname = 'api_finca_municipio_id_fkey'
                    ) THEN
                        ALTER TABLE api_finca 
                        ADD CONSTRAINT api_finca_municipio_id_fkey 
                        FOREIGN KEY (municipio_id) 
                        REFERENCES catalogos_municipio(id) 
                        ON DELETE RESTRICT;
                    END IF;
                END $$;
            """,
            reverse_sql="""
                ALTER TABLE api_finca 
                DROP CONSTRAINT IF EXISTS api_finca_municipio_id_fkey;
            """
        ),
        # Step 8: Update Django state to reflect ForeignKey
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='finca',
                    name='municipio',
                    field=models.ForeignKey(
                        help_text='Municipio donde se encuentra la finca',
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='fincas',
                        to='catalogos.municipio'
                    ),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddIndex(
            model_name='finca',
            index=models.Index(fields=['municipio'], name='api_finca_municip_43980f_idx'),
        ),
    ]
