# Generated by Django 5.2.9 on 2025-12-10 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0017_temaparametro_and_more'),
        ('fincas_app', '0024_convert_lote_to_bulto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='descripcion',
            field=models.TextField(blank=True, default='', help_text='Descripción adicional o notas sobre el bulto'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='estado',
            field=models.ForeignKey(blank=True, help_text='Estado del procesamiento del bulto (Recibido, En fermentación, Fermentado, Secado, Listo para análisis, Analizado)', limit_choices_to={'tema__codigo': 'TEMA_ESTADO_LOTE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes_estado', to='catalogos.parametro'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='finca',
            field=models.ForeignKey(help_text='Finca de origen del bulto de granos', on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='fincas_app.finca'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='nombre',
            field=models.CharField(help_text='Nombre o descripción del bulto', max_length=200),
        ),
        migrations.AlterField(
            model_name='lote',
            name='variedad',
            field=models.ForeignKey(help_text='Variedad de cacao del bulto', limit_choices_to={'tema__codigo': 'TEMA_VARIEDAD_CACAO'}, on_delete=django.db.models.deletion.PROTECT, related_name='lotes_variedad', to='catalogos.parametro'),
        ),
    ]
