# Generated by Django 5.2.9 on 2025-12-11 05:29
# Modified: Added existence checks since these constraints may have been removed in migration 0024

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fincas_app', '0025_alter_lote_descripcion_alter_lote_estado_and_more'),
    ]

    operations = [
        # Remove constraints only if they exist (they may have been removed in migration 0024)
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM pg_constraint 
                        WHERE conname = 'fincas_app_lote_area_positiva'
                    ) THEN
                        ALTER TABLE fincas_app_lote DROP CONSTRAINT fincas_app_lote_area_positiva;
                    END IF;
                END $$;
            """,
            reverse_sql="-- Cannot reverse constraint removal"
        ),
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM pg_constraint 
                        WHERE conname = 'fincas_app_lote_fecha_cosecha_valida'
                    ) THEN
                        ALTER TABLE fincas_app_lote DROP CONSTRAINT fincas_app_lote_fecha_cosecha_valida;
                    END IF;
                END $$;
            """,
            reverse_sql="-- Cannot reverse constraint removal"
        ),
        # Update Django state to reflect constraint removal
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='lote',
                    name='fincas_app_lote_area_positiva',
                ),
                migrations.RemoveConstraint(
                    model_name='lote',
                    name='fincas_app_lote_fecha_cosecha_valida',
                ),
            ],
            database_operations=[],
        ),
    ]
