# Generated by Django 4.2.7 on 2025-10-30 02:30
# -*- coding: utf-8 -*-

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingEmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_sent', models.DateTimeField(auto_now=True)),
                ('temp_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Verificación Pendiente de Email',
                'verbose_name_plural': 'Verificaciones Pendientes de Email',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'otp_code'], name='auth_app_pe_email_81d42a_idx'), models.Index(fields=['created_at'], name='auth_app_pe_created_5a4851_idx')],
            },
        ),
    ]


