# Generated by Django 5.2.5 on 2025-08-31 21:15

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único del usuario', primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Dirección de correo electrónico (será el username)', max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('role', models.CharField(choices=[('farmer', 'Agricultor'), ('admin', 'Administrador'), ('analyst', 'Analista')], default='farmer', help_text='Rol del usuario en el sistema', max_length=20, verbose_name='Rol')),
                ('phone_number', models.CharField(blank=True, help_text='Número de teléfono de contacto', max_length=20, validators=[django.core.validators.RegexValidator(message="Número de teléfono debe tener formato: '+999999999'. Hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('is_verified', models.BooleanField(default=False, help_text='Indica si el email del usuario ha sido verificado', verbose_name='Email verificado')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, help_text='Región geográfica del usuario', max_length=100, verbose_name='Región')),
                ('municipality', models.CharField(blank=True, help_text='Municipio donde se encuentra el usuario', max_length=100, verbose_name='Municipio')),
                ('farm_name', models.CharField(blank=True, help_text='Nombre de la finca (solo para agricultores)', max_length=200, verbose_name='Nombre de la finca')),
                ('years_experience', models.PositiveIntegerField(blank=True, help_text='Años de experiencia en cultivo de cacao', null=True, verbose_name='Años de experiencia')),
                ('farm_size_hectares', models.DecimalField(blank=True, decimal_places=2, help_text='Tamaño de la finca en hectáreas', max_digits=10, null=True, verbose_name='Tamaño de finca (hectáreas)')),
                ('preferred_language', models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', max_length=10, verbose_name='Idioma preferido')),
                ('email_notifications', models.BooleanField(default=True, help_text='Recibir notificaciones por correo electrónico', verbose_name='Notificaciones por email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='auth_user_email_ece7f7_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='auth_user_role_f90fd2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'role'], name='auth_user_is_acti_6f67f4_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['region'], name='users_userp_region_b6f82c_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['municipality'], name='users_userp_municip_66dc00_idx'),
        ),
    ]
