# Generated by Django 4.2.7 on 2025-10-29 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del tema (ej: TIPO_DOC)', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre del tema (ej: Tipo de Documento)', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del tema', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el tema está activo')),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['codigo'], name='catalogos_t_codigo_641465_idx'), models.Index(fields=['activo'], name='catalogos_t_activo_e797a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código del parámetro (ej: CC, M, F)', max_length=20)),
                ('nombre', models.CharField(help_text='Nombre del parámetro (ej: Cédula de Ciudadanía)', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional del parámetro', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el parámetro está activo')),
                ('tema', models.ForeignKey(help_text='Tema al que pertenece este parámetro', on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='catalogos.tema')),
            ],
            options={
                'verbose_name': 'Parámetro',
                'verbose_name_plural': 'Parámetros',
                'ordering': ['tema', 'codigo'],
                'indexes': [models.Index(fields=['tema', 'codigo'], name='catalogos_p_tema_id_b9c145_idx'), models.Index(fields=['activo'], name='catalogos_p_activo_1cef5f_idx')],
                'unique_together': {('tema', 'codigo')},
            },
        ),
    ]


