# Generated by Django 4.2.7 on 2025-10-29 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='CÃ³digo del departamento (ej: 05 para Antioquia)', max_length=10, unique=True)),
                ('nombre', models.CharField(help_text='Nombre del departamento', max_length=100)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='CÃ³digo del municipio', max_length=10)),
                ('nombre', models.CharField(help_text='Nombre del municipio', max_length=100)),
                ('departamento', models.ForeignKey(help_text='Departamento al que pertenece el municipio', on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='catalogos.departamento')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['departamento', 'nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='departamento',
            index=models.Index(fields=['codigo'], name='catalogos_d_codigo_dee94e_idx'),
        ),
        migrations.AddIndex(
            model_name='departamento',
            index=models.Index(fields=['nombre'], name='catalogos_d_nombre_83d1a4_idx'),
        ),
        migrations.AddIndex(
            model_name='municipio',
            index=models.Index(fields=['departamento', 'codigo'], name='catalogos_m_departa_0888b1_idx'),
        ),
        migrations.AddIndex(
            model_name='municipio',
            index=models.Index(fields=['nombre'], name='catalogos_m_nombre_d6cab3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='municipio',
            unique_together={('departamento', 'codigo')},
        ),
    ]


