apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-namespace

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - ingress.yaml
  - backend-deployment.yaml
  - media-pvc.yaml
  - redis.yaml
  - redis-pvc.yaml
  - networkpolicy.yaml
  - ../db/k8s/deployment.yaml
  - ../db/k8s/service.yaml
  - ../db/k8s/pvc.yaml
  - ../frontend/k8s/deployment.yaml
  - ../frontend/k8s/service.yaml
  - ../celery/k8s/deployment.yaml

