apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: app-namespace
type: Opaque
stringData:
  DB_NAME: "cacaoscan_db"
  DB_USER: "postgres"
  DB_PASSWORD: "CHANGE_THIS_PASSWORD"
  SECRET_KEY: "CHANGE_THIS_SECRET_KEY"
  REDIS_PASSWORD: "CHANGE_THIS_REDIS_PASSWORD"
  CELERY_BROKER_URL: "redis://:CHANGE_THIS_REDIS_PASSWORD@redis-service:6379/0"
  CELERY_RESULT_BACKEND: "redis://:CHANGE_THIS_REDIS_PASSWORD@redis-service:6379/0"

---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: app-namespace
type: Opaque
stringData:
  POSTGRES_DB: "cacaoscan_db"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "CHANGE_THIS_PASSWORD"

