# Generated by Django 4.2.7 on 2025-11-25 14:22
# -*- coding: utf-8 -*-

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

# SQL constant for no-op migrations
NOOP_SQL = "SELECT 1;"


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0001_add_modelmetrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(help_text='ID único del trabajo', max_length=100, unique=True)),
                ('job_type', models.CharField(choices=[('regression', 'Modelo de Regresión'), ('vision', 'Modelo de Visión (YOLOv8)'), ('incremental', 'Entrenamiento Incremental')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'Ejecutándose'), ('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('model_name', models.CharField(help_text='Nombre del modelo a entrenar', max_length=100)),
                ('dataset_size', models.PositiveIntegerField(help_text='Número de imágenes en el dataset')),
                ('epochs', models.PositiveIntegerField(default=100)),
                ('batch_size', models.PositiveIntegerField(default=16)),
                ('learning_rate', models.FloatField(default=0.001)),
                ('config_params', models.JSONField(default=dict, help_text='Parámetros adicionales de configuración')),
                ('metrics', models.JSONField(default=dict, help_text='Métricas de entrenamiento')),
                ('model_path', models.CharField(blank=True, help_text='Ruta del modelo entrenado', max_length=500, null=True)),
                ('logs', models.TextField(blank=True, help_text='Logs del entrenamiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si falló')),
                ('progress_percentage', models.FloatField(default=0.0, help_text='Porcentaje de progreso')),
            ],
            options={
                'verbose_name': 'Trabajo de Entrenamiento',
                'verbose_name_plural': 'Trabajos de Entrenamiento',
                'ordering': ['-created_at'],
            },
        ),
        # ModelMetrics indexes and unique_together - only update state, don't touch database
        # The table structure is already correct from api migrations
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='modelmetrics',
                    name='api_modelme_model_n_617b8b_idx',
                ),
                migrations.RemoveIndex(
                    model_name='modelmetrics',
                    name='api_modelme_model_t_9928c0_idx',
                ),
                migrations.RemoveIndex(
                    model_name='modelmetrics',
                    name='api_modelme_metric__74fb4f_idx',
                ),
                migrations.RemoveIndex(
                    model_name='modelmetrics',
                    name='api_modelme_created_5e9c32_idx',
                ),
                migrations.RemoveIndex(
                    model_name='modelmetrics',
                    name='api_modelme_is_best_730ec5_idx',
                ),
                migrations.RemoveIndex(
                    model_name='modelmetrics',
                    name='api_modelme_is_prod_fa489d_idx',
                ),
                migrations.AlterUniqueTogether(
                    name='modelmetrics',
                    unique_together=set(),
                ),
            ],
            database_operations=[
                # Table structure is already correct from api migrations
                # Only update Django's state, don't modify the database
                migrations.RunSQL(NOOP_SQL, reverse_sql=NOOP_SQL),
            ],
        ),
        # ModelMetrics field alterations - only update state, don't touch database
        # The table structure is already correct from api migrations
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='modelmetrics',
                    name='additional_metrics',
                    field=models.JSONField(default=dict),
                ),
                migrations.AlterField(
                    model_name='modelmetrics',
                    name='batch_size',
                    field=models.PositiveIntegerField(),
                ),
                migrations.AlterField(
                    model_name='modelmetrics',
                    name='dataset_size',
                    field=models.PositiveIntegerField(),
                ),
                migrations.AlterField(
                    model_name='modelmetrics',
                    name='epochs',
                    field=models.PositiveIntegerField(),
                ),
                migrations.AlterField(
                    model_name='modelmetrics',
                    name='inference_time_ms',
                    field=models.FloatField(blank=True, null=True),
                ),
                migrations.AlterField(
                    model_name='modelmetrics',
                    name='is_best_model',
                    field=models.BooleanField(default=False),
                ),
                migrations.AlterField(
                    model_name='modelmetrics',
                    name='is_production_model',
                    field=models.BooleanField(default=False),
                ),
                migrations.AlterField(
                    model_name='modelmetrics',
                    name='knowledge_retention',
                    field=models.FloatField(blank=True, null=True),
                ),
                migrations.AlterField(
                    model_name='modelmetrics',
                    name='learning_rate',
                    field=models.FloatField(),
                ),
                migrations.AlterField(
                    model_name='modelmetrics',
                    name='mae',
                    field=models.FloatField(),
                ),
                migrations.AlterField(
                    model_name='modelmetrics',
                    name='mape',
                    field=models.FloatField(blank=True, null=True),
                ),
                migrations.AlterField(
                    model_name='modelmetrics',
                    name='model_name',
                    field=models.CharField(max_length=100),
                ),
                migrations.AlterField(
                    model_name='modelmetrics',
                    name='model_params',
                    field=models.JSONField(default=dict),
                ),
                migrations.AlterField(
                    model_name='modelmetrics',
                    name='mse',
                    field=models.FloatField(),
                ),
                migrations.AlterField(
                    model_name='modelmetrics',
                    name='notes',
                    field=models.TextField(blank=True),
                ),
                migrations.AlterField(
                    model_name='modelmetrics',
                    name='r2_score',
                    field=models.FloatField(),
                ),
                migrations.AlterField(
                    model_name='modelmetrics',
                    name='rmse',
                    field=models.FloatField(),
                ),
                migrations.AlterField(
                    model_name='modelmetrics',
                    name='stability_score',
                    field=models.FloatField(blank=True, null=True),
                ),
                migrations.AlterField(
                    model_name='modelmetrics',
                    name='target',
                    field=models.CharField(choices=[('alto', 'Altura'), ('ancho', 'Ancho'), ('grosor', 'Grosor'), ('peso', 'Peso'), ('calidad', 'Calidad'), ('variedad', 'Variedad')], max_length=20),
                ),
                migrations.AlterField(
                    model_name='modelmetrics',
                    name='test_size',
                    field=models.PositiveIntegerField(),
                ),
                migrations.AlterField(
                    model_name='modelmetrics',
                    name='train_size',
                    field=models.PositiveIntegerField(),
                ),
                migrations.AlterField(
                    model_name='modelmetrics',
                    name='training_time_seconds',
                    field=models.PositiveIntegerField(blank=True, null=True),
                ),
                migrations.AlterField(
                    model_name='modelmetrics',
                    name='validation_size',
                    field=models.PositiveIntegerField(),
                ),
                migrations.AlterField(
                    model_name='modelmetrics',
                    name='version',
                    field=models.CharField(max_length=20),
                ),
            ],
            database_operations=[
                # Table structure is already correct from api migrations
                # Only update Django's state, don't modify the database
                migrations.RunSQL(NOOP_SQL, reverse_sql=NOOP_SQL),
            ],
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='trainingjob',
            index=models.Index(fields=['status'], name='training_tr_status_9bf3d8_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingjob',
            index=models.Index(fields=['job_type'], name='training_tr_job_typ_60ebf4_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingjob',
            index=models.Index(fields=['created_by', '-created_at'], name='training_tr_created_6c8fea_idx'),
        ),
    ]
