# Generated by Django 5.2.8 on 2025-12-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_trainingjob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingjob',
            name='model_path',
            field=models.CharField(blank=True, default='', help_text='Ruta del modelo entrenado', max_length=500),
        ),
    ]
