# Generated by Django 5.2.8 on 2025-12-01 17:24
# -*- coding: utf-8 -*-

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_fix_non_nullable_fields_temporary_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelmetrics',
            name='batch_size',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='modelmetrics',
            name='dataset_size',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='modelmetrics',
            name='epochs',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='modelmetrics',
            name='learning_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='modelmetrics',
            name='mae',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='modelmetrics',
            name='metric_type',
            field=models.CharField(choices=[('training', 'Métricas de Entrenamiento'), ('validation', 'Métricas de Validación'), ('test', 'Métricas de Prueba'), ('incremental', 'Métricas Incrementales')], max_length=20),
        ),
        migrations.AlterField(
            model_name='modelmetrics',
            name='model_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='modelmetrics',
            name='model_type',
            field=models.CharField(choices=[('regression', 'Modelo de Regresión'), ('classification', 'Modelo de Clasificación'), ('segmentation', 'Modelo de Segmentación'), ('incremental', 'Modelo Incremental')], max_length=20),
        ),
        migrations.AlterField(
            model_name='modelmetrics',
            name='mse',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='modelmetrics',
            name='r2_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='modelmetrics',
            name='rmse',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='modelmetrics',
            name='target',
            field=models.CharField(choices=[('alto', 'Altura'), ('ancho', 'Ancho'), ('grosor', 'Grosor'), ('peso', 'Peso'), ('calidad', 'Calidad'), ('variedad', 'Variedad')], max_length=20),
        ),
        migrations.AlterField(
            model_name='modelmetrics',
            name='test_size',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='modelmetrics',
            name='train_size',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='modelmetrics',
            name='validation_size',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='modelmetrics',
            name='version',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingjob',
            name='dataset_size',
            field=models.PositiveIntegerField(help_text='Número de imágenes en el dataset'),
        ),
        migrations.AlterField(
            model_name='trainingjob',
            name='job_id',
            field=models.CharField(help_text='ID único del trabajo', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='trainingjob',
            name='job_type',
            field=models.CharField(choices=[('regression', 'Modelo de Regresión'), ('vision', 'Modelo de Visión (YOLOv8)'), ('incremental', 'Entrenamiento Incremental')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingjob',
            name='model_name',
            field=models.CharField(help_text='Nombre del modelo a entrenar', max_length=100),
        ),
    ]
