# Generated by Django 4.2.7 on 2025-10-29 14:45
# -*- coding: utf-8 -*-

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fincas_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacaoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='cacao_images/processed/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('finca', models.CharField(blank=True, max_length=200, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('variedad', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_cosecha', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('lote', models.ForeignKey(blank=True, help_text='Lote al que pertenece esta imagen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cacao_images', to='fincas_app.lote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_app_cacao_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imagen de Cacao',
                'verbose_name_plural': 'Imágenes de Cacao',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CacaoPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alto_mm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ancho_mm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('grosor_mm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('peso_g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('confidence_alto', models.DecimalField(decimal_places=3, default=0.0, max_digits=4)),
                ('confidence_ancho', models.DecimalField(decimal_places=3, default=0.0, max_digits=4)),
                ('confidence_grosor', models.DecimalField(decimal_places=3, default=0.0, max_digits=4)),
                ('confidence_peso', models.DecimalField(decimal_places=3, default=0.0, max_digits=4)),
                ('processing_time_ms', models.PositiveIntegerField(help_text='Tiempo de procesamiento en milisegundos')),
                ('crop_url', models.URLField(blank=True, help_text='URL del crop procesado', max_length=500, null=True)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('device_used', models.CharField(choices=[('cpu', 'CPU'), ('cuda', 'GPU CUDA'), ('mps', 'Apple Silicon')], default='cpu', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='images_app.cacaoimage')),
            ],
            options={
                'verbose_name': 'Predicción de Cacao',
                'verbose_name_plural': 'Predicciones de Cacao',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['image'], name='images_app__image_i_42ebb9_idx'), models.Index(fields=['-created_at'], name='images_app__created_0c256a_idx'), models.Index(fields=['model_version'], name='images_app__model_v_d66094_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='cacaoimage',
            index=models.Index(fields=['user', '-created_at'], name='images_app__user_id_d9ac53_idx'),
        ),
        migrations.AddIndex(
            model_name='cacaoimage',
            index=models.Index(fields=['processed'], name='images_app__process_6134c4_idx'),
        ),
        migrations.AddIndex(
            model_name='cacaoimage',
            index=models.Index(fields=['region', 'finca'], name='images_app__region_8368ba_idx'),
        ),
    ]


