# Generated by Django 4.2.7 on 2025-10-31 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fincas_app', '0003_rename_fincas_app__agricul_396b5b_idx_api_finca_agricul_f9cee8_idx_and_more'),
        ('images_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cacaoimage',
            new_name='images_app__region_efbff0_idx',
            old_name='images_app__region_8368ba_idx',
        ),
        migrations.AddField(
            model_name='cacaoimage',
            name='finca_nombre',
            field=models.CharField(blank=True, help_text='Nombre de la finca (campo de respaldo)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cacaoimage',
            name='finca',
            field=models.ForeignKey(blank=True, help_text='Finca a la que pertenece esta imagen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cacao_images', to='fincas_app.finca'),
        ),
        migrations.AlterField(
            model_name='cacaoimage',
            name='image',
            field=models.ImageField(upload_to='dataset/'),
        ),
    ]
