# Generated by Django 5.2.8 on 2025-12-01 17:24
# -*- coding: utf-8 -*-

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_app', '0004_fix_non_nullable_fields_temporary_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cacaoprediction',
            name='analysis_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', help_text='Estado del análisis', max_length=20),
        ),
        migrations.AddField(
            model_name='cacaoprediction',
            name='defects_count',
            field=models.PositiveIntegerField(default=0, help_text='Número de defectos detectados'),
        ),
        migrations.AddField(
            model_name='cacaoprediction',
            name='maturity_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de madurez', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='cacaoprediction',
            name='processing_time',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tiempo de procesamiento en segundos', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='cacaoprediction',
            name='quality_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Puntuación de calidad', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='cacaoprediction',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la predicción', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cacaoprediction',
            name='alto_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='cacaoprediction',
            name='ancho_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='cacaoprediction',
            name='grosor_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='cacaoprediction',
            name='peso_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='cacaoprediction',
            name='processing_time_ms',
            field=models.PositiveIntegerField(blank=True, help_text='Tiempo de procesamiento en milisegundos', null=True),
        ),
    ]
