# Generated by Django 5.2.5 on 2025-08-31 15:45

import apps.images.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CacaoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Imagen del grano de cacao para análisis', upload_to=apps.images.models.upload_cacao_image, verbose_name='Imagen del grano')),
                ('width', models.DecimalField(blank=True, decimal_places=3, help_text='Ancho del grano en milímetros', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Ancho (mm)')),
                ('height', models.DecimalField(blank=True, decimal_places=3, help_text='Alto del grano en milímetros', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Alto (mm)')),
                ('thickness', models.DecimalField(blank=True, decimal_places=3, help_text='Grosor del grano en milímetros', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Grosor (mm)')),
                ('weight', models.DecimalField(blank=True, decimal_places=4, help_text='Peso del grano en gramos', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Peso (g)')),
                ('quality_score', models.DecimalField(blank=True, decimal_places=3, help_text='Puntuación de calidad calculada por ML (0.0 - 1.0)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Puntuación de calidad')),
                ('predicted_quality', models.CharField(choices=[('excellent', 'Excelente'), ('good', 'Bueno'), ('fair', 'Regular'), ('poor', 'Deficiente'), ('unknown', 'Desconocido')], default='unknown', help_text='Calidad predicha por el modelo de ML', max_length=20, verbose_name='Calidad predicha')),
                ('defect_type', models.CharField(choices=[('none', 'Sin defecto'), ('mold', 'Moho'), ('insect_damage', 'Daño por insectos'), ('broken', 'Roto'), ('germinated', 'Germinado'), ('flat', 'Plano'), ('purple', 'Púrpura'), ('slaty', 'Pizarroso'), ('other', 'Otro')], default='none', help_text='Tipo de defecto detectado en el grano', max_length=20, verbose_name='Tipo de defecto')),
                ('defect_confidence', models.DecimalField(blank=True, decimal_places=3, help_text='Nivel de confianza en la detección del defecto (0.0 - 1.0)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Confianza del defecto')),
                ('image_width', models.PositiveIntegerField(blank=True, help_text='Ancho de la imagen en píxeles', null=True, verbose_name='Ancho de imagen (px)')),
                ('image_height', models.PositiveIntegerField(blank=True, help_text='Alto de la imagen en píxeles', null=True, verbose_name='Alto de imagen (px)')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Tamaño del archivo de imagen en bytes', null=True, verbose_name='Tamaño del archivo (bytes)')),
                ('is_processed', models.BooleanField(default=False, help_text='Indica si la imagen ha sido procesada por ML', verbose_name='Procesada')),
                ('processing_time', models.DecimalField(blank=True, decimal_places=3, help_text='Tiempo que tomó procesar la imagen en segundos', max_digits=8, null=True, verbose_name='Tiempo de procesamiento (s)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Fecha de actualización')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el grano', verbose_name='Notas')),
                ('batch_number', models.CharField(blank=True, help_text='Número de lote al que pertenece el grano', max_length=100, verbose_name='Número de lote')),
                ('origin', models.CharField(blank=True, help_text='Origen geográfico del grano', max_length=200, verbose_name='Origen')),
                ('harvest_date', models.DateField(blank=True, help_text='Fecha de cosecha del grano', null=True, verbose_name='Fecha de cosecha')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='Usuario que subió la imagen', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Imagen de Cacao',
                'verbose_name_plural': 'Imágenes de Cacao',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CacaoImageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='Nombre del modelo ML utilizado para el análisis', max_length=100, verbose_name='Nombre del modelo')),
                ('model_version', models.CharField(help_text='Versión del modelo ML utilizado', max_length=50, verbose_name='Versión del modelo')),
                ('confidence_scores', models.JSONField(default=dict, help_text='Puntuaciones de confianza para cada clase', verbose_name='Puntuaciones de confianza')),
                ('feature_vector', models.JSONField(default=list, help_text='Vector de características extraído por el modelo', verbose_name='Vector de características')),
                ('processing_metadata', models.JSONField(default=dict, help_text='Información adicional sobre el procesamiento', verbose_name='Metadatos de procesamiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del análisis', verbose_name='Fecha de análisis')),
                ('image', models.ForeignKey(help_text='Imagen de cacao analizada', on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='images.cacaoimage', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Análisis de Imagen',
                'verbose_name_plural': 'Análisis de Imágenes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cacaoimage',
            index=models.Index(fields=['created_at'], name='images_caca_created_ee4e99_idx'),
        ),
        migrations.AddIndex(
            model_name='cacaoimage',
            index=models.Index(fields=['predicted_quality'], name='images_caca_predict_2a4389_idx'),
        ),
        migrations.AddIndex(
            model_name='cacaoimage',
            index=models.Index(fields=['defect_type'], name='images_caca_defect__f3f57e_idx'),
        ),
        migrations.AddIndex(
            model_name='cacaoimage',
            index=models.Index(fields=['batch_number'], name='images_caca_batch_n_11cfc2_idx'),
        ),
        migrations.AddIndex(
            model_name='cacaoimage',
            index=models.Index(fields=['is_processed'], name='images_caca_is_proc_034393_idx'),
        ),
        migrations.AddIndex(
            model_name='cacaoimageanalysis',
            index=models.Index(fields=['model_name'], name='images_caca_model_n_35ae62_idx'),
        ),
        migrations.AddIndex(
            model_name='cacaoimageanalysis',
            index=models.Index(fields=['created_at'], name='images_caca_created_22a861_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cacaoimageanalysis',
            unique_together={('image', 'model_name', 'model_version')},
        ),
    ]
