# Generated by Django 4.2.7 on 2025-10-29 03:30
# -*- coding: utf-8 -*-

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código del género', max_length=5, unique=True)),
                ('nombre', models.CharField(help_text='Nombre del género', max_length=30)),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código del tipo de documento', max_length=5, unique=True)),
                ('nombre', models.CharField(help_text='Nombre del tipo de documento', max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(help_text='Municipio', max_length=100)),
                ('departamento', models.CharField(help_text='Departamento', max_length=100)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['departamento', 'municipio'],
                'unique_together': {('municipio', 'departamento')},
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(help_text='Número de documento de identidad', max_length=20, unique=True)),
                ('primer_nombre', models.CharField(help_text='Primer nombre', max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, help_text='Segundo nombre (opcional)', max_length=50, null=True)),
                ('primer_apellido', models.CharField(help_text='Primer apellido', max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, help_text='Segundo apellido (opcional)', max_length=50, null=True)),
                ('telefono', models.CharField(help_text='Número de teléfono', max_length=15)),
                ('direccion', models.CharField(blank=True, help_text='Dirección de residencia', max_length=255, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Fecha de nacimiento', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('genero', models.ForeignKey(help_text='Género', on_delete=django.db.models.deletion.PROTECT, to='personas.genero')),
                ('tipo_documento', models.ForeignKey(help_text='Tipo de documento de identidad', on_delete=django.db.models.deletion.PROTECT, to='personas.tipodocumento')),
                ('ubicacion', models.ForeignKey(blank=True, help_text='Ubicación geográfica', null=True, on_delete=django.db.models.deletion.SET_NULL, to='personas.ubicacion')),
                ('user', models.OneToOneField(help_text='Usuario asociado a la persona', on_delete=django.db.models.deletion.CASCADE, related_name='persona', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['primer_apellido', 'primer_nombre'],
            },
        ),
    ]


