# Generated by Django 4.2.7 on 2025-10-29 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_departamento_municipio_and_more'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ubicacion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='persona',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='persona',
            name='departamento',
            field=models.ForeignKey(blank=True, help_text='Departamento de residencia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas', to='catalogos.departamento'),
        ),
        migrations.AddField(
            model_name='persona',
            name='municipio',
            field=models.ForeignKey(blank=True, help_text='Municipio de residencia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas', to='catalogos.municipio'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='genero',
            field=models.ForeignKey(help_text='ParÃ¡metro del catÃ¡logo SEXO (ej: M, F, O)', limit_choices_to={'tema__codigo': 'SEXO'}, on_delete=django.db.models.deletion.PROTECT, related_name='personas_genero', to='catalogos.parametro'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipo_documento',
            field=models.ForeignKey(help_text='ParÃ¡metro del catÃ¡logo TIPO_DOC (ej: CC, CE, PA, TI, RC)', limit_choices_to={'tema__codigo': 'TIPO_DOC'}, on_delete=django.db.models.deletion.PROTECT, related_name='personas_tipo_doc', to='catalogos.parametro'),
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.DeleteModel(
            name='TipoDocumento',
        ),
        migrations.DeleteModel(
            name='Ubicacion',
        ),
    ]


