# Generated by Django 4.2.7 on 2025-10-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_alter_ubicacion_unique_together_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['numero_documento'], name='personas_pe_numero__8c4625_idx'),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['user'], name='personas_pe_user_id_0b4abb_idx'),
        ),
    ]
