# Generated by Django 4.2.7 on 2025-10-30 01:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_alter_ubicacion_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email del usuario pendiente de registro', max_length=254, unique=True)),
                ('data', models.JSONField(help_text='Datos del formulario de registro en formato JSON')),
                ('verification_token', models.UUIDField(default=uuid.uuid4, help_text='Token Ãºnico de verificaciÃ³n', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creaciÃ³n del registro pendiente')),
                ('is_verified', models.BooleanField(default=False, help_text='Indica si el correo ya fue verificado')),
                ('verified_at', models.DateTimeField(blank=True, help_text='Fecha y hora de verificaciÃ³n', null=True)),
            ],
            options={
                'verbose_name': 'Registro Pendiente',
                'verbose_name_plural': 'Registros Pendientes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='personas_pe_email_baf3e6_idx'), models.Index(fields=['verification_token'], name='personas_pe_verific_12f52c_idx'), models.Index(fields=['is_verified', 'created_at'], name='personas_pe_is_veri_cf73fc_idx')],
            },
        ),
    ]


