# Generated by Django 4.2.7 on 2025-10-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_persona_personas_pe_numero__8c4625_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(help_text='NÃºmero de telÃ©fono (Ãºnico)', max_length=15, unique=True),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['telefono'], name='personas_pe_telefon_c9eac3_idx'),
        ),
    ]


