# Generated by Django 4.2.7 on 2025-10-30 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_pendingregistration'),
        ('personas', '0004_alter_persona_telefono_and_more'),
    ]

    operations = [
    ]


