# Generated by Django 5.2.8 on 2025-12-01 17:24
# -*- coding: utf-8 -*-

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0007_fix_non_nullable_fields_temporary_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='numero_documento',
            field=models.CharField(help_text='Número de documento de identidad', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='primer_apellido',
            field=models.CharField(help_text='Primer apellido', max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='primer_nombre',
            field=models.CharField(help_text='Primer nombre', max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(help_text='Número de teléfono (único)', max_length=15, unique=True),
        ),
    ]
