"""
Views module for CacaoScan API.
Organized by domain for better maintainability.
Re-exports views from modular apps for backward compatibility.
"""
# Import views from modular apps
from auth_app.views import (
    LoginView,
    RegisterView,
    LogoutView,
    UserProfileView,
    RefreshTokenView,
    ChangePasswordView,
    EmailVerificationView,
    ResendVerificationView,
    PreRegisterView,
    VerifyEmailPreRegistrationView,
    ForgotPasswordView,
    ResetPasswordView,
    SendOtpView,
    VerifyOtpView,
    UserListView,
    UserUpdateView,
    UserDeleteView,
    UserStatsView,
    AdminStatsView,
    UserDetailView,
)

from images_app.views import (
    ScanMeasureView,
    ImagesListView,
    ImageDetailView,
    ImagesStatsView,
    ImageUpdateView,
    ImageDeleteView,
    ImageDownloadView,
    ImagesExportView,
    AdminImagesListView,
    AdminImageDetailView,
    AdminImageUpdateView,
    AdminImageDeleteView,
    AdminBulkUpdateView,
    AdminDatasetStatsView,
    ImagePermissionMixin,
    BatchAnalysisView,
)

from fincas_app.views import (
    FincaListCreateView,
    FincaDetailView,
    FincaUpdateView,
    FincaDeleteView,
    FincaActivateView,
    FincaStatsView,
    LoteListCreateView,
    LoteDetailView,
    LoteUpdateView,
    LoteDeleteView,
    LoteStatsView,
    LotesPorFincaView,
)

from reports.views import (
    ReporteListCreateView,
    ReporteDetailView,
    ReporteDownloadView,
    ReporteDeleteView,
    ReporteStatsView,
    ReporteCleanupView,
    ReporteAgricultoresView,
    ReporteUsuariosView,
)

# Import views that remain in api/views
from .notifications import (
    NotificationListCreateView, NotificationDetailView,
    NotificationMarkReadView, NotificationMarkAllReadView,
    NotificationUnreadCountView, NotificationStatsView,
    NotificationCreateView,
)
from .admin import (
    ActivityLogListView, LoginHistoryListView, AuditStatsView,
    SystemSettingsView, SystemGeneralConfigView, SystemSecurityConfigView,
    SystemMLConfigView, SystemInfoView,
    TaskStatusView,
)
from .ml import (
    CalibrationStatusView, CalibrationView, CalibratedScanMeasureView,
    IncrementalTrainingStatusView, IncrementalTrainingView,
    IncrementalDataUploadView, IncrementalModelVersionsView,
    IncrementalDataVersionsView,
    ModelMetricsListView, ModelMetricsDetailView, ModelMetricsCreateView,
    ModelMetricsUpdateView, ModelMetricsDeleteView, ModelMetricsStatsView,
    ModelPerformanceTrendView, ModelComparisonView, BestModelsView,
    ProductionModelsView,
    # Model views
    ModelsStatusView,
    DatasetValidationView,
    LoadModelsView,
    AutoInitializeView,
    LatestMetricsView,
    PromoteModelView,
    AutoTrainView,
    # Training views
    TrainingJobListView,
    TrainingJobCreateView,
    TrainingJobStatusView,
)
__all__ = [
    # Auth views
    'LoginView',
    'RegisterView',
    'LogoutView',
    'UserProfileView',
    'RefreshTokenView',
    'ChangePasswordView',
    'EmailVerificationView',
    'ResendVerificationView',
    'PreRegisterView',
    'VerifyEmailPreRegistrationView',
    'ForgotPasswordView',
    'ResetPasswordView',
    # Image views
    'ScanMeasureView',
    'ImagesListView',
    'ImageDetailView',
    'ImagesStatsView',
    'ImageUpdateView',
    'ImageDeleteView',
    'ImageDownloadView',
    'ImagesExportView',
    'AdminImagesListView',
    'AdminImageDetailView',
    'AdminImageUpdateView',
    'AdminImageDeleteView',
    'AdminBulkUpdateView',
    'AdminDatasetStatsView',
    'ImagePermissionMixin',
    # User views (moved to auth module)
    'UserListView',
    'UserUpdateView',
    'UserDeleteView',
    'UserStatsView',
    'AdminStatsView',
    'UserDetailView',
    # Training views (moved to ml module)
    'TrainingJobListView',
    'TrainingJobCreateView',
    'TrainingJobStatusView',
    # ML views (moved to ml module)
    'ModelsStatusView',
    'DatasetValidationView',
    'LoadModelsView',
    'AutoInitializeView',
    'LatestMetricsView',
    'PromoteModelView',
    'AutoTrainView',
    # Finca views
    'FincaListCreateView',
    'FincaDetailView',
    'FincaUpdateView',
    'FincaDeleteView',
    'FincaActivateView',
    'FincaStatsView',
    'LoteListCreateView',
    'LoteDetailView',
    'LoteUpdateView',
    'LoteDeleteView',
    'LoteStatsView',
    'LotesPorFincaView',
    # Auth OTP views
    'SendOtpView',
    'VerifyOtpView',
    # Notification views
    'NotificationListCreateView',
    'NotificationDetailView',
    'NotificationMarkReadView',
    'NotificationMarkAllReadView',
    'NotificationUnreadCountView',
    'NotificationStatsView',
    'NotificationCreateView',
    # Admin views
    'ActivityLogListView',
    'LoginHistoryListView',
    'AuditStatsView',
    'SystemSettingsView',
    'SystemGeneralConfigView',
    'SystemSecurityConfigView',
    'SystemMLConfigView',
    'SystemInfoView',
    'TaskStatusView',
    # Report views
    'ReporteListCreateView',
    'ReporteDetailView',
    'ReporteDownloadView',
    'ReporteDeleteView',
    'ReporteStatsView',
    'ReporteCleanupView',
    'ReporteAgricultoresView',
    'ReporteUsuariosView',
    # ML views (calibration, incremental, metrics)
    'CalibrationStatusView',
    'CalibrationView',
    'CalibratedScanMeasureView',
    'IncrementalTrainingStatusView',
    'IncrementalTrainingView',
    'IncrementalDataUploadView',
    'IncrementalModelVersionsView',
    'IncrementalDataVersionsView',
    'ModelMetricsListView',
    'ModelMetricsDetailView',
    'ModelMetricsCreateView',
    'ModelMetricsUpdateView',
    'ModelMetricsDeleteView',
    'ModelMetricsStatsView',
    'ModelPerformanceTrendView',
    'ModelComparisonView',
    'BestModelsView',
    'ProductionModelsView',
    # Image batch views
    'BatchAnalysisView',
]

