# Generated by Django 5.2.8 on 2025-12-01 17:24
# -*- coding: utf-8 -*-

from django.conf import settings
from django.db import migrations, models


def rename_activitylog_indexes_if_exist(apps, schema_editor):
    """Rename ActivityLog indexes if they exist in the database, or create them if they don't."""
    connection = schema_editor.connection
    
    with connection.cursor() as cursor:
        # Handle user_id_timestamp index
        cursor.execute("""
            SELECT 1 FROM pg_indexes 
            WHERE tablename = 'api_activitylog' 
            AND indexname = 'api_activit_user_id_timestamp_idx'
        """)
        
        if cursor.fetchone():
            # Index exists, rename it
            cursor.execute('ALTER INDEX "api_activit_user_id_timestamp_idx" RENAME TO "api_activit_user_id_7d2450_idx"')
        else:
            # Check if new index already exists
            cursor.execute("""
                SELECT 1 FROM pg_indexes 
                WHERE tablename = 'api_activitylog' 
                AND indexname = 'api_activit_user_id_7d2450_idx'
            """)
            if not cursor.fetchone():
                # Create the index with new name
                cursor.execute("""
                    CREATE INDEX IF NOT EXISTS api_activit_user_id_7d2450_idx 
                    ON api_activitylog (user_id, timestamp DESC)
                """)
        
        # Handle action index
        cursor.execute("""
            SELECT 1 FROM pg_indexes 
            WHERE tablename = 'api_activitylog' 
            AND indexname = 'api_activit_action_idx'
        """)
        
        if cursor.fetchone():
            # Index exists, rename it
            cursor.execute('ALTER INDEX "api_activit_action_idx" RENAME TO "api_activit_action_961c51_idx"')
        else:
            # Check if new index already exists
            cursor.execute("""
                SELECT 1 FROM pg_indexes 
                WHERE tablename = 'api_activitylog' 
                AND indexname = 'api_activit_action_961c51_idx'
            """)
            if not cursor.fetchone():
                # Create the index with new name
                cursor.execute("""
                    CREATE INDEX IF NOT EXISTS api_activit_action_961c51_idx 
                    ON api_activitylog (action)
                """)
        
        # Handle resource index
        cursor.execute("""
            SELECT 1 FROM pg_indexes 
            WHERE tablename = 'api_activitylog' 
            AND indexname = 'api_activit_resource_idx'
        """)
        
        if cursor.fetchone():
            # Index exists, rename it
            cursor.execute('ALTER INDEX "api_activit_resource_idx" RENAME TO "api_activit_resourc_2ecce8_idx"')
        else:
            # Check if new index already exists
            cursor.execute("""
                SELECT 1 FROM pg_indexes 
                WHERE tablename = 'api_activitylog' 
                AND indexname = 'api_activit_resourc_2ecce8_idx'
            """)
            if not cursor.fetchone():
                # Create the index with new name
                cursor.execute("""
                    CREATE INDEX IF NOT EXISTS api_activit_resourc_2ecce8_idx 
                    ON api_activitylog (resource_type, resource_id)
                """)


def reverse_rename_activitylog_indexes(apps, schema_editor):
    """Reverse the index renames."""
    connection = schema_editor.connection
    
    with connection.cursor() as cursor:
        # Reverse user_id_timestamp index
        cursor.execute("""
            SELECT 1 FROM pg_indexes 
            WHERE tablename = 'api_activitylog' 
            AND indexname = 'api_activit_user_id_7d2450_idx'
        """)
        if cursor.fetchone():
            cursor.execute('ALTER INDEX "api_activit_user_id_7d2450_idx" RENAME TO "api_activit_user_id_timestamp_idx"')
        
        # Reverse action index
        cursor.execute("""
            SELECT 1 FROM pg_indexes 
            WHERE tablename = 'api_activitylog' 
            AND indexname = 'api_activit_action_961c51_idx'
        """)
        if cursor.fetchone():
            cursor.execute('ALTER INDEX "api_activit_action_961c51_idx" RENAME TO "api_activit_action_idx"')
        
        # Reverse resource index
        cursor.execute("""
            SELECT 1 FROM pg_indexes 
            WHERE tablename = 'api_activitylog' 
            AND indexname = 'api_activit_resourc_2ecce8_idx'
        """)
        if cursor.fetchone():
            cursor.execute('ALTER INDEX "api_activit_resourc_2ecce8_idx" RENAME TO "api_activit_resource_idx"')


def remove_loginhistory_indexes_if_exist(apps, schema_editor):
    """Remove LoginHistory indexes if they exist."""
    connection = schema_editor.connection
    
    with connection.cursor() as cursor:
        # Remove user_id index
        cursor.execute("""
            SELECT 1 FROM pg_indexes 
            WHERE tablename = 'api_loginhistory' 
            AND indexname = 'api_loginhi_user_id_19e442_idx'
        """)
        if cursor.fetchone():
            cursor.execute('DROP INDEX IF EXISTS "api_loginhi_user_id_19e442_idx"')
        
        # Remove login_successful index
        cursor.execute("""
            SELECT 1 FROM pg_indexes 
            WHERE tablename = 'api_loginhistory' 
            AND indexname = 'api_loginhi_login_s_78b423_idx'
        """)
        if cursor.fetchone():
            cursor.execute('DROP INDEX IF EXISTS "api_loginhi_login_s_78b423_idx"')


def reverse_remove_loginhistory_indexes(apps, schema_editor):
    """Reverse - recreate indexes (not typically needed)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_fix_non_nullable_fields_temporary_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Remove LoginHistory indexes conditionally
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='loginhistory',
                    name='api_loginhi_user_id_19e442_idx',
                ),
                migrations.RemoveIndex(
                    model_name='loginhistory',
                    name='api_loginhi_login_s_78b423_idx',
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    remove_loginhistory_indexes_if_exist,
                    reverse_remove_loginhistory_indexes
                ),
            ],
        ),
        # Rename ActivityLog indexes conditionally
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name='activitylog',
                    new_name='api_activit_user_id_7d2450_idx',
                    old_name='api_activit_user_id_timestamp_idx',
                ),
                migrations.RenameIndex(
                    model_name='activitylog',
                    new_name='api_activit_action_961c51_idx',
                    old_name='api_activit_action_idx',
                ),
                migrations.RenameIndex(
                    model_name='activitylog',
                    new_name='api_activit_resourc_2ecce8_idx',
                    old_name='api_activit_resource_idx',
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    rename_activitylog_indexes_if_exist,
                    reverse_rename_activitylog_indexes
                ),
            ],
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(help_text='Acción realizada', max_length=100),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='failure_reason',
            field=models.CharField(blank=True, help_text='Razón del fallo si no fue exitoso', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Dirección IP del usuario', null=True),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='user_agent',
            field=models.TextField(blank=True, default='', help_text='User Agent del navegador'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['user', '-login_time'], name='api_loginhi_user_id_735807_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['login_successful'], name='api_loginhi_login_s_afd012_idx'),
        ),
    ]
