# Generated by Django 5.2.8 on 2025-12-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_remove_loginhistory_api_loginhi_user_id_19e442_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='failure_reason',
            field=models.CharField(blank=True, default='', help_text='Razón del fallo si no fue exitoso', max_length=200),
        ),
    ]
